contact_links:
  - name: SteamOS Waydroid Install Guide
    url: https://www.youtube.com/watch?v=06T-h-jPVx8
    about: YouTube video on installing
  - name: SteamOS Waydroid Upgrade Guide
    url: https://www.youtube.com/watch?v=CJAMwIb_oI0
    about: YouTube video on upgrading
